project_id = "xmhwvmzpbomgkeavjerk"

[functions.export-csv]
verify_jwt = false

[functions.import-cards]
verify_jwt = false

[functions.list-cards-admin]
verify_jwt = false

[functions.batch-update-learnings]
verify_jwt = false

[functions.fetch-study-cards]
verify_jwt = false

[functions.fetch-programs]
verify_jwt = false

[functions.upload-media]
verify_jwt = false

[functions.recent-lessons]
verify_jwt = false
